apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iris-ml-service-hpa-restricted
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris-ml-service
  minReplicas: 1
  # This restricts the scaler to 1 pod to force the bottleneck
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60